# Basic Hugo Config
BaseURL = "https://connectwithmusa.com/"
languageCode = "en-us"
title = "Musa Ahmed"
theme = "hyde"
enableEmoji = true
enableRobotsTXT = true
rssLimit = 100
#summaryLength = 70

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true

[Menus]
# Menu entry items with less/smaller weight are ordered first.
  main = [
      {Name = "🏠 Home", URL = "/", weight = 1},
      {Name = "📄 About", URL = "/about", weight = 2},
      {Name = "✍️ All Posts", URL = "/posts", weight = 3},
      {Name = "📔 RSS", URL = "/index.xml", weight = 4}
  ]

  contact = [
      {Name = "📧 Email", URL = "mailto:connectwithmusa@protonmail.com", weight = 1},
      {Name = "🖥️ Github", URL = "https://github.com/m-GDEV", weight = 2},
      {Name = "💼 LinkedIn", URL = "https://www.linkedin.com/in/musa-ahmed-239a97203", weight = 3}
  ]

# User created and defined config params
[params]
  Author = "Musa Ahmed"
  description = "Musa Ahmed's personal website and blog."
  sidebarImage = "/images/whoami/me.webp"
  sidebarImageDesc = "Cool logo used as placeholder for proper image."
  themeColor = "theme-purple"
  layoutReverse = false
  #disqusShortname = "spf13"
  #googleAnalytics = "Your tracking code"
  # Put the value of the src attribute in the snippet provided in the var below.
  plausibleAnalytics = "https://analytics.connectwithmusa.com/js/plausible.js"
  copyright = "Made with ❤️ · Since 2021"



     #GitHub = "xxxx"
    #Linkedin = ""
    #Twitter = "xxxx"
    #Instagram = "xxxx"
    #Facebook = "xxxx"
    #Telegram = "xxxx"
    #Medium = ""
    #Gitlab = ""
    #Youtubelegacy = ""
    #Youtubecustom = ""
    #Youtubechannel = ""
    #Tumblr = ""
    #Quora = ""
    #Keybase = ""
    #Pinterest = ""
    #Reddit = ""
    #Codepen = ""
    #FreeCodeCamp = ""
    #Bitbucket = ""
    #Stackoverflow = ""
    #Weibo = ""
    #Odnoklassniki = ""
    #VK = ""
    #Flickr = ""
    #Xing = ""
    #Snapchat = ""
    #Soundcloud = ""
    #Spotify = ""
    #Bandcamp = ""
    #Paypal = ""
    #Fivehundredpx = ""
    #Mix = ""
    #Goodreads = ""
    #Lastfm = ""
    #Foursquare = ""
    #Hackernews = ""
    #Kickstarter = ""
    #Patreon = ""
    #Steam = ""
    #Twitch = ""
    #Strava = ""
    #Skype = ""
    #Whatsapp = ""
    #Zhihu = ""
    #Douban = ""
    #Angellist = ""
    #Slidershare = ""
    #Jsfiddle = ""
    #Deviantart = ""
    #Behance = ""
    #Dribbble = ""
    #Wordpress = ""
    #Vine = ""
    #Googlescholar = ""
    #Researchgate = ""
    #Mastodon = ""
    #Thingiverse = ""
    #Devto = ""
    #Gitea = ""
    #XMPP = ""
    #Matrix = ""
    #Bilibili = ""
    #Email = "xxxx@xxxx.com"
